src/utils/cordic/internal/absolute_value.v
src/utils/cordic/internal/constants.v
src/utils/cordic/internal/CORDIC_Rotation_top.v
src/utils/cordic/internal/CORDIC_Vectoring_top1.v
src/utils/cordic/internal/ip_upscale.v
src/utils/cordic/internal/micro_rot_gen.v
src/utils/cordic/internal/op_downscale.v
src/utils/cordic/internal/output_scale.v
src/utils/cordic/internal/quad_chk.v
src/utils/cordic/internal/rot_block_first_stage.v
src/utils/cordic/internal/rot_block_last_stage.v
src/utils/cordic/internal/rot_block.v
src/utils/cordic/internal/SCICA_CORDIC_wrapper.v
src/utils/cordic/internal/vec_angle_calc.v
src/utils/cordic/internal/vec_block_first_stage.v
src/utils/cordic/internal/vec_block_last_stage.v
src/utils/cordic/internal/vec_block.v
src/utils/cordic/internal/vec_op_downscale.v
src/utils/cordic/internal/vec_quad_check.v
src/utils/cordic/internal/vec_scaling.v
src/utils/cordic/cordic_doubly_pipe_top.v
src/top/theta_block/theta_block.v
